### PR TITLE
Fix Symbols as name attribute broken with chef-client 12.5

### LINKED ISSUE #35: Symbols as name attribute broken with chef-client 12.5
With chef-client 12.5, if you try to do this:

```
backup_model :jenkins_home do
  ...
end
```
You get:
```
ERROR: Option name must be a kind of [Symbol]!  You passed "jenkins_home".
```
@vancluever raised this as an issue (https://github.com/chef/chef/issues/4047) in the chef repo and confirmed its a problem with this cookbook.

### PR DESCRIPTION
**Pull request by tucksaun**
Should fix #35

### CODE REVIEW

**Comment by cnunciato** [comment]
Hit this myself today. Any chance of getting it merged?

**Comment by jwmarshall** [comment]
Broken in chef 12.6, would love to see this merged

**Comment by nickptrvc** [comment]
Ran into this today. Chef 12.7.

**Comment by hirocaster** [comment]
Broken in chef now version.
merge, please. > @joshcramer @mbiang @smith

**Comment by allaire** [comment]
@smith Can you take a look :)

**Comment by hernan82arg** [comment]
@smith @joshcramer @mbiang hi guys, could you please merge this? Thanks a lot.

**Comment by smith** [comment]
@hernan82arg merged. @guilhem should be able to handle cutting a new release probably.

**Comment by guilhem** [comment]
@smith I've just give you ownership of backup cookbook on supermarket.
Have Fun :)

**Comment by smith** [comment]
I'm already a maintainer. I recall that I handed off ownership to you, because I no longer use this cookbook. I can go ahead and make a release though, but only because I was @-mentioned directly in this pull request. Otherwise I don't even watch this repo anymore.

**Comment by guilhem** [comment]
@smith same here :/

**Comment by smith** [comment]
@guilhem so goes the life of an open source programmer. It's a lifetime commitment! HAHAHA :)

**Comment by smith** [comment]
Released https://supermarket.chef.io/cookbooks/backup/versions/1.3.1

(BTW is anybody would like to take over as maintainer of this cookbook please contact me at smith@chef.io)

**Pull request merged**
